version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Bangkok
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Bangkok
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    rebase-strategy: auto

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Bangkok
    groups:
      docker-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    rebase-strategy: auto
